### ISSUE TITLE
Fails to launch with 1.5.0

### ISSUE THREAD

**Issue by Boy0000** [darmiel/fuzzy-mc#1]
Getting the following error on startup with version 1.5.0, 1.4.0 seemingly did not have this
When disabling Fuzzy, game starts without issues

![image](https://github.com/darmiel/fuzzy-mc/assets/62521371/be5c7ecf-473c-4c13-9521-9191c0364c27)

**Comment by darmiel** [comment]
Hi @Boy0000, thanks for the report! I'll look into this.

As I currently cannot reproduce the error, can you give me the following information?
Did you use version 1.4.0 before upgrading to 1.5.0? What Minecraft Version do you use? Can you show me your `fuzzy.json` config? (`.minecraft/config/fuzzy.json`)

**Comment by Boy0000** [comment]
1. I believe i used 1.4.0 first, but not too sure
2. Reverting to 1.4.0 right nbow launches everything fine
3. 1.20.2
4. config from 1.4.0 successfull boot
```json
{
  "fuzzySearchCutoff": 0,
  "fuzzySearchLimit": 100,
  "clearOnJoin": false,
  "showScore": true,
  "enableShiftActions": true,
  "enableCommandBlockSync": true
}
```

**Comment by darmiel** [comment]
Thanks! I'll let you know when I've fixed it.

**Comment by Boy0000** [comment]
Sidenote: Updating to 1.5.0 and deleting fuzzy.json did not fix the problem, same error

**Comment by darmiel** [comment]
I have released `v1.5.1`, please let me know if this fixed your problem :)
https://modrinth.com/mod/fuzzy/version/OcrCANmL

**Comment by Boy0000** [comment]
seems to have fixed it! thanks for the quick fix 👍 love the mod

![image](https://github.com/darmiel/fuzzy-mc/assets/62521371/958804a6-23ac-44eb-8392-027607f0caba)

**Comment by darmiel** [comment]
awesome, thank you!
